routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "TodosController@index");
Route::resource("todo", "TodosController");

app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TodosController.php
<?php

namespace App\Http\Controllers;

use App\rest\HttpClientInterface;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Redirect;

class TodosController extends Controller
{
    /**
     * @var \App\rest\HttpClientInterface $client
     */
    private $client;
    /**
     * @var string $object object
     */
    private $object;

    /**
     * TodosController constructor.
     * @param HttpClientInterface $client http client
     */
    public function __construct(HttpClientInterface $client)
    {
        $this->client = $client;
        $this->object = config('objects.todo');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view("todo.index")->with(['todos' => $this->client->get($this->object)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view("todo.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request request object
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $data = [
            'task' => $request->get('task', null),
            'done' => (bool)$request->get('done', false),
        ];

        $this->client->post($this->object, $data);

        \request()->session()->flash("message", "Task created");

        return Redirect::route("todo.index");
    }

    /**
     * Display the specified resource.
     * @param int $id id
     * @return Response
     */
    public function show($id)
    {
        $task = $this->client->get($this->object, $id);

        return view("todo.show")->with(['todo' => $task]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id id
     * @return Response
     */
    public function edit($id)
    {
        $data = $this->client->get($this->object, $id);
        $task = null;
        if (isset($data)) {
            $task = $data;
        }

        return view("todo.edit")->with(['todo' => $task]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request Request object
     * @param int $id id
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $data = [
            'task' => $request->get('task', null),
            'done' => (bool)$request->get('done', false),
        ];

        $this->client->patch($this->object, $id, $data);
        \request()->session()->flash("message", "Task updated");

        return Redirect::route("todo.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $this->client->delete($this->object, $id);
        \request()->session()->flash("message", "Task deleted");

        return Redirect::route("todo.index");
    }
}

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" media="screen" href="app.css" />
    <script src="app.js"></script>
</head>
<body>
 
 <div class="container">
     @if (Session::has('message'))
         <div class="alert alert-info">{{ Session::get('message') }}</div>
     @endif
        @yield("content")
 </div>

</body>
</html>

resources/views/todo/create.blade.php
@extends('layouts.master')

@section("content")
    <h2>Creating a task</h2>

    <form action="{{route("todo.store")}}" method="post">
        @csrf
        <div>
            <h2>Task</h2>
            <textarea name="task"></textarea><br>
            Done: <select name="done">
                <option value=0>No</option>
                <option value=1>yes</option>
            </select>
            <br>

        </div>

        <br>
        <button type="submit" class="btn bg-success">Create</button>
    </form>

@endsection

resources/views/todo/edit.blade.php
@extends('layouts.master')

@section('content')
    <h1>Edit Task</h1>
    @if(empty($todo))
        <p>No task to edit</p>

    @else
        <form action="{{ route('todo.update', $todo['id']) }}" method="POST">
            @method('PATCH')
            @csrf
            <table class="table table-stripped">
                <thead>
                <th>No</th>
                <th>Task</th>
                <th>Done</th>
                </thead>
                <tr>
                    <td><textarea name="task">{{$todo['task']}} </textarea></td>
                    <td>
                        <select name="done">
                            <option value=0>No</option>
                            <option value=1>yes</option>
                        </select>
                    </td>
                    </td>
                </tr>
            </table>
            <button class="btn btn-outline-success" type="submit">Save</button>
        </form>
    @endif
@endsection

resources/views/todo/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="m-md-2">
        <h1>Todos</h1>
        <a class="btn btn-success float-left" href="{{route("todo.create")}}">Create Task</a>
    </div>
    <table class="table table-stripped">
        <thead>
        <th>Id</th>
        <th>Task</th>
        <th>Done</th>
        <th>Edit</th>
        <th>Delete</th>
        </thead>
        @foreach($todos as $index => $todo)
            <tr>
                <td>{{$todo['id']}}</td>
                <td>{{$todo['task']}}</td>
                <td>{{ $todo['done'] ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{route("todo.edit", $todo['id'])}}" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <form method="POST" action="{{route('todo.destroy', $todo['id'])}}"> @csrf  @method('DELETE')
                        <button class="btn btn-danger"> Delete</button>
                    </form>
                </td>

            </tr>
        @endforeach
    </table>
@endsection

resources/views/todo/show.blade.php
@extends('layouts.master')

@section('content')
    <h2>Show page</h2>


    <p>Id: {{ $todo['id'] }}</p>
    <p></p>
    <p>Task: {{ $todo['task'] }}</p>

    <p>Done: {{ $todo['done'] }}</p>
@endsection